import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const {Presentation,PresentationFile}=await import(path.join(process.env.RUNTIME_NODE_MODULES,'@oai/artifact-tool/dist/artifact_tool.mjs'));
const skill=process.env.PRESENTATIONS_SKILL_DIR;
const python=process.env.RUNTIME_PYTHON;
const {finalizePresentation}=await import(path.join(skill,'container_tools/artifact_tool_utils.mjs'));
const root=path.resolve(import.meta.dirname,'../..');
const video=path.resolve(process.argv[2]);
const workspace=path.join(root,'output/demo/video-slides');
const build=path.join(workspace,'build');
await fs.mkdir(build,{recursive:true});
await fs.mkdir(path.join(workspace,'final'),{recursive:true});
const poster=path.join(build,'poster.png');
execFileSync('ffmpeg',['-v','error','-y','-ss','22','-i',video,'-frames:v','1',poster]);
const deck=Presentation.create({slideSize:{width:1280,height:720}});
const slide=deck.slides.add();
slide.background.fill='#2B3034';
const heading=slide.shapes.add({geometry:'textbox',position:{left:64,top:40,width:1152,height:70},fill:'none',line:{fill:'none',width:0}});
heading.text='CLI 端到端演示';
heading.text.style={typeface:'PingFang SC',fontSize:46,color:'#FFFFFF',bold:true,autoFit:'none'};
slide.images.add({blob:new Uint8Array(await fs.readFile(poster)),contentType:'image/png',alt:'video:cli-demo',fit:'contain',position:{left:160,top:140,width:960,height:540}});
slide.speakerNotes.textFrame.setText('附录视频。依次展示视觉处理、语音转写与降噪、音乐分轨。播放速度为 1 倍，模型已提前准备。音乐原曲：Karissa Hobbs, Let\'s Go Fishin\', CC-BY-3.0。CLI 命令、输入散列、推理输出与录制时间线保存在对应 recordings 目录。');
await (await PresentationFile.exportPptx(deck)).save(path.join(build,'layout.pptx'));
const preview=await deck.export({slide,format:'png',scale:1});
await fs.writeFile(path.join(build,'slide-18.png'),new Uint8Array(await preview.arrayBuffer()));
const manifest=path.join(build,'media.json');
await fs.writeFile(manifest,JSON.stringify([{id:'cli-demo',poster,video,sha256:crypto.createHash('sha256').update(await fs.readFile(video)).digest('hex')}],null,2));
execFileSync(python,[path.join(root,'scripts/embed_slide_audio.py'),path.join(build,'layout.pptx'),path.join(build,'video.pptx'),manifest],{stdio:'inherit'});
const candidate = path.join(build,'candidate-'+Date.now()+'.pptx');
execFileSync(python,[path.join(root,'scripts/demo-video/append_slide.py'),path.join(root,'docs/slides/Specialist-OS-AHA-v5.pptx'),path.join(build,'video.pptx'),candidate],{stdio:'inherit'});
const tableOwners=[2,4,12,14,15,16];
await finalizePresentation({workspaceDir:workspace,candidatePath:candidate,finalPath:path.join(workspace,'final/Specialist-OS-AHA-v6.pptx'),pythonExecutable:python,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit',...tableOwners.flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:18,requiredNativeTableOwnerSlides:tableOwners,requiredNativeChartOwnerSlides:[11],fontPolicy:{basis:'design',families:['PingFang SC']},verifyArtifactToolImport:true,receiptPath:path.join(build,'validation.json')});
console.log(path.join(workspace,'final/Specialist-OS-AHA-v6.pptx'));
